# Generated by Django 5.1.3 on 2024-11-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='overview1',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='overview2',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='whatsapp',
            new_name='profession',
        ),
        migrations.AddField(
            model_name='courses',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
