# Generated by Django 5.1.3 on 2024-11-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_instructors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructors',
        ),
    ]
