# Generated by Django 5.1.3 on 2024-11-16 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_instructors_course_instructors_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructors',
            name='course',
        ),
    ]
