# Generated by Django 5.1.3 on 2024-11-17 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_instructors_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructors',
            name='course',
        ),
    ]
