# Generated by Django 5.1.3 on 2024-11-17 13:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_remove_instructors_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='course',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
