# Generated by Django 5.1.3 on 2024-11-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0012_instructors_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password_text',
            new_name='profession',
        ),
        migrations.RemoveField(
            model_name='user',
            name='place',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tokenone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tokentwo',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.TextField(null=True, unique=True),
        ),
    ]
