# Generated by Django 5.1.3 on 2024-11-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0014_user_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
